---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Build backend-api container image
    community.general.docker_image:
      build:
        path: /api-service
      name: gcr.io/{{ gcp_project }}/ai5project:austin-pet-alive-api-service
      source: build
  - name: Push backend-api image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/ai5project:austin-pet-alive-api-service
      repository: gcr.io/{{ gcp_project }}/ai5project:austin-pet-alive-api-service
      push: yes
      source: local
  - name: Build frontend container image
    community.general.docker_image:
      build:
        path: /frontend-react
      name: gcr.io/{{ gcp_project }}/ai5project:austin-pet-alive-frontend-react
      source: build
  - name: Push frontend image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/ai5project:austin-pet-alive-frontend-react
      repository: gcr.io/{{ gcp_project }}/ai5project:austin-pet-alive-frontend-react
      push: yes
      source: local
